In [4]:
import numpy as np
from numpy.ma.core import arange

arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
import random as rd

a = np.random.randint(1,101,size=(3,4))
a

array([[12, 45, 79, 86],
       [84, 36, 31, 13],
       [ 9, 80, 77, 32]], dtype=int32)

In [11]:
b = np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
c = np.linspace(0,2*np.pi,10)
c

[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


In [32]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
d

d[1,2]

d[2,0]

d[d>5]

copy = d.copy()
copy[copy % 2 == 0] = 0
copy

mean = np.mean(d,axis=0)
mean

array([4., 5., 6.])

In [38]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

A * B

A @ B

det = np.linalg.det(A)
det

inv = np.linalg.inv(A)
inv

eig = np.linalg.eig(A)
eig

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [2]:
import numpy as np
d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
means = np.mean(d,axis=0)
centr = d - means
centr

array([[-4.5, -4.5, -4.5],
       [-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5],
       [ 4.5,  4.5,  4.5]])

In [5]:
arr = np.arange(5)
ar = np.tile(arr,(5,1))
ar

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [7]:
g = np.arange(5).reshape(1,5) * np.ones((5,1))
g

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [9]:
f = np.arange(12).reshape(4,3)
f

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])